### ISSUE TITLE
'Worker' object has no attribute 'apk_fn' problem

### ISSUE THREAD

**Issue by papachristoumarios** [Hanga/hanga-cli#4]
Hello! You are doing an outstanding work out there! However, I am having the following issue:
When I am trying to build an app, I get the following error:
`'Worker' object has no attribute 'apk_fn'`
What might be happening? 
Thanks in advance
![screenshot from 2014-09-09 10 45 36](https://cloud.githubusercontent.com/assets/918216/4198146/5086f7be-37f5-11e4-8541-0d8261602f40.png)

**Comment by tito** [comment]
Hi, the issue is just before the last one: you missed to add the version in the main.py. the last error should hidden. Thanks for reporting!
